name: Clark Kampfe
markdown: redcarpet
highlighter: pygments

# resume data
resume_datas:
  - header: currently
    contents:
      - Belly ;; Junior Software Engineer

  - header: education
    contents:
      - Dev Bootcamp ;; 9-week intensive web developer program
      - Gustavus Adolphus College ;; political science

  - header: experience
    contents:
      - Tunisia Live ;; photojournalist
      - The Gustavian Weekly ;; photography editor
      - Integration Objects ;; marketing assistant

  - header: skills
    contents:
      - ruby, javascript/coffeescript, SQL (postgresql, sqlite), BDD, git, html5/css

  - header: interests
    contents:
      - Angular, SQL, APIs, Backbone, CoffeeScript
