name: Clark Kampfe
markdown: redcarpet
highlighter: pygments

# resume data
resume_datas:
  - header: currently
    contents:
      - Belly ;; Data Engineer

  - header: education
    contents:
      - Dev Bootcamp ;; 9-week intensive web developer program
      - Gustavus Adolphus College ;; political science

  - header: experience
    contents:
      - Tunisia Live ;; photojournalist
      - The Gustavian Weekly ;; photography editor
      - Integration Objects ;; marketing assistant

  - header: skills
    contents:
      - Scala, SQL, Ruby, JavaScript

  - header: interests
    contents:
      - Clojure, Elixir
