name: Clark Kampfe
markdown: redcarpet
highlighter: pygments

# resume data
resume_datas:
  - header: currently
    contents:
      - Belly ;; Junior Software Engineer

  - header: education
    contents:
      - Dev Bootcamp ;; 9-week intensive web developer program
      - Gustavus Adolphus College ;; political science

  - header: experience
    contents:
      - Tunisia Live ;; photojournalist
      - The Gustavian Weekly ;; photography editor
      - Integration Objects ;; marketing assistant

  - header: skills
    contents:
      - Ruby, JavaScript/CoffeeScript, SQL (Postgresql, MySQL, SQLite), BDD, Git, HTML5/CSS

  - header: interests
    contents:
      - Scala, Erlang, SQL, functional programming
